### ISSUE TITLE
bump to 1.12

### ISSUE THREAD

**Issue by aolko** [JonnyNova/SmartMoving#6]
will you make a version for 1.12?

**Comment by JonnyNova** [comment]
No, this depends on PlayerAPI and Divisor has been keeping that relatively up to date. Maybe when it is updated I might update this.

**Comment by ScienceDrummer** [comment]
PlayerAPI has been updated to 1.12.1

**Comment by aolko** [comment]
so, is it compatible?

**Comment by ScienceDrummer** [comment]
I have no idea, but if someone wants to try to port it and smart moving to 1.12.2 they could attempt to do so. I'm no good at coding or else I would have done so myself.

**Comment by aolko** [comment]
me thinks this problem is eternal

**Comment by Julian-MM** [comment]
I've waited so long for this mod to be updated is this hope i see?

2018-05-14 7:23 GMT+02:00 aolko <notifications@github.com>:

**Comment by ScienceDrummer** [comment]
Should I open a new request to port to 1.12.2?

**Comment by Julian-MM** [comment]
yes

2018-05-15 16:53 GMT+02:00 ScienceDrummer <notifications@github.com>:

**Comment by ScienceDrummer** [comment]
It appears someone finally ported it, and it actually working on a rewritten version of the mod, but he might have forgotten about it.
